name: Update Payment Link

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run script
        run: python bot.py
        env:
          RIALIT_API_KEY: ${{ secrets.RIALIT_API_KEY }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          CALLBACK_URL: "https://meek-nougat-8fbb56.netlify.app/callback"
          AMOUNT: 100000
